version: "2.2"
services:
  postgres:
    image: postgres:15-alpine
    hostname: postgres
    environment:
      POSTGRES_USER: "greenlight"
      POSTGRES_PASSWORD: "greenlight"
      POSTGRES_DB: "greenlight"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  mailtrap:
    image: eaudeweb/mailtrap
    environment:
      POSTGRES_USER: "greenlight"
      POSTGRES_PASSWORD: "greenlight"
      POSTGRES_DB: "greenlight"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "8081:80"
      - "2525:25"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local